artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Venura-94/Venura-94-End-to-End-ML-Project/raw/main/Red%20Wine%20Quality%20Data%20Set.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
